# Generated by Django 6.0.3 on 2026-03-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso_estudantes_matricula_delete_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='email_contato',
        ),
    ]
