# Generated by Django 6.0.3 on 2026-03-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_matricula_email_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudantes',
            name='matricula',
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.estudantes'),
            preserve_default=False,
        ),
    ]
