# Generated by Django 6.0.3 on 2026-03-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_estudantes_matricula_matricula_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estudantes'),
        ),
    ]
