# Generated by Django 6.0.3 on 2026-03-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_matricula_estudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='matricula_id',
            field=models.IntegerField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estudantes', unique=True),
        ),
    ]
